/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto01archivos;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author criss
 */
public class FormAbrirArchivo extends javax.swing.JFrame {

    /**
     * Creates new form FormAbrirArchivo
     */
    public FormAbrirArchivo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        seleccionar = new javax.swing.JButton();
        autor = new javax.swing.JTextField();
        Creador = new javax.swing.JTextField();
        FechaCreacion = new javax.swing.JTextField();
        FechaModificacion = new javax.swing.JTextField();
        Productor = new javax.swing.JTextField();
        version = new javax.swing.JTextField();
        tamanio = new javax.swing.JTextField();
        numeroPaginas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tamanioPaginas = new javax.swing.JTextField();
        imagenes = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fuentes = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        nombreArchivo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();

        jLabel3.setText("Autor:");

        jLabel9.setText("Productor:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seleccionar.setText("Seleccionar");
        seleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarMouseClicked(evt);
            }
        });

        Creador.setEditable(false);

        FechaCreacion.setEditable(false);

        FechaModificacion.setEditable(false);

        Productor.setEditable(false);

        version.setEditable(false);

        tamanio.setEditable(false);

        numeroPaginas.setEditable(false);

        jLabel1.setText("Fecha Modificacion:");

        jLabel2.setText("Creador:");

        jLabel4.setText("Autor:");

        jLabel5.setText("Productor:");

        jLabel6.setText("Fecha Creacion:");

        jLabel7.setText("Version de PDF:");

        jLabel8.setText("Tamaño del archivo:");

        jLabel10.setText("Tamaño de paginas:");

        jLabel11.setText("Numero de paginas: ");

        tamanioPaginas.setEditable(false);

        imagenes.setEditable(false);

        jLabel12.setText("Listado Imagenes:");

        jLabel13.setText("Listado Fuentes:");

        fuentes.setEditable(false);
        fuentes.setColumns(20);
        fuentes.setRows(5);
        jScrollPane1.setViewportView(fuentes);

        jLabel14.setText("Palabras clave:");

        jTextField11.setEditable(false);

        jLabel15.setText("Nombre de Archivo:");

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                            .addComponent(Productor)
                            .addComponent(FechaModificacion)
                            .addComponent(FechaCreacion)
                            .addComponent(Creador)
                            .addComponent(autor)
                            .addComponent(nombreArchivo)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tamanioPaginas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(numeroPaginas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                                        .addComponent(tamanio, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(version, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(imagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Creador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Productor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tamanioPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarMouseClicked
        // TODO add your handling code here:
        String temp = "";
        JFileChooser pdfruta = new JFileChooser();
        pdfruta.setDialogTitle("Seleccione la carpeta");
        pdfruta.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if(pdfruta.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            File archivo = pdfruta.getSelectedFile();
            if(archivo.isDirectory())
            {
                lectorCarpetas(archivo);
            }
            else if (archivo.isFile())
            {
                System.out.println(archivo.getName());
                lectorArchivosPDF(archivo);
            }
        }
    }//GEN-LAST:event_seleccionarMouseClicked

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        EscritorArchivo escritor = new EscritorArchivo();
        escritor.setNombre(nombreArchivo.getText());
        escritor.setAutor(autor.getText());
        escritor.setCreador(Creador.getText());
        escritor.setFechaCreacion(FechaCreacion.getText());
        escritor.setFechaModificacion(FechaModificacion.getText());
        escritor.setProductor(Productor.getText());
        escritor.setVersion(version.getText());
        escritor.setTamanio(tamanio.getText());
        escritor.setPaginas(numeroPaginas.getText());
        escritor.setTamanioPaginas(tamanioPaginas.getText());
        escritor.setImagenes(imagenes.getText());
        escritor.setFuentes(fuentes.getText());
        escritor.escrituraAleatoria();
        System.out.println("Se guardo correctamente");
    }//GEN-LAST:event_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAbrirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAbrirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAbrirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAbrirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAbrirArchivo().setVisible(true);
            }
        });
    }
    
    private void lectorCarpetas(File archivo)
    {
        String temp = "";
        for (final File fileEntry : archivo.listFiles()) 
            {
             if (fileEntry.isDirectory()) {
            System.out.println("leyendo archivos de la caarpeta " + archivo.getAbsolutePath());
            lectorCarpetas(fileEntry);
              } else {
                if (fileEntry.isFile()) {
                temp = fileEntry.getName();
                 if ((temp.substring(temp.lastIndexOf('.') + 1, temp.length()).toLowerCase()).equals("pdf"))
                 {
                     System.out.println("----------------------------------");
                     System.out.println("Leyendo el pdf: " + fileEntry.getName());
                     String aux = archivo.getAbsolutePath()+ "\\" + fileEntry.getName();
                     File archivopdf = new File(aux);
                     lectorArchivosPDF(archivopdf);
                 }
                }

                }
           }
    }
     
    private void lectorArchivosPDF(File archivo)
    {
          LectorPDF lector = new LectorPDF(archivo);
          int a = lector.LecturaMetaDatos().split("/").length;
          String[] partir = lector.LecturaMetaDatos().split("/");
          //System.out.println("Los metadatos son:");
          this.nombreArchivo.setText(archivo.getName());
          String b = "";
          String c = "";
          boolean parentesis = false;
           for(int j=1; j<a; j++)
          {
           b = "";
           c = "";
           parentesis = false;
           //System.out.println(partir[j]);
             for(int i=1; i<partir[j].length(); i++)
             {
                 if(partir[j].charAt(i-1) ==  '(')
                 {
                     parentesis = true;
                 }
                  if(parentesis)   
                  {
                     if(partir[j].charAt(i) !=  ')')
                     {
                         b+=partir[j].charAt(i);
                     }
                     else{
                         parentesis = false;
                         break;
                     }
                  }
                  else{
                      c+=partir[j].charAt(i-1);
                  }
             }
             //System.out.println(c);
             if("Author".equals(c) || "Author ".equals(c))
             {
                 //System.out.println("Autor: " + b);
                 this.autor.setText(b);
             }
             else if("Creator".equals(c) || "Creator ".equals(c))
             {
                 //System.out.println("Creador: " + b);
                 this.Creador.setText(b);
             }
             else if("CreationDate".equals(c) || "CreationDate ".equals(c))
             {
                 //System.out.println("Fecha Creacion: " + b);
                 this.FechaCreacion.setText(b);
             }
             else if("ModDate".equals(c) || "ModDate ".equals(c))
             {
                 //System.out.println("Fecha Modificacion: " + b);
                 this.FechaModificacion.setText(b);
             }
             else if("Producer".equals(c) || "Producer ".equals(c))
             {
                 //System.out.println("Productor: " + b);
                 this.Productor.setText(b);
             }
             else if("Title".equals(c) || "Title ".equals(c))
             {
                 //System.out.println("Titulo: " + b);
                 //this.autor.setText(b);
             }
             System.out.println(b);
          }
           
          System.out.println("La version del PDF es: " + lector.LecturaVersion());
          System.out.println("Tamaño del archivo: " + lector.Tamanio() + " Bytes");
          System.out.println("Número de Páginas: "+lector.Numpaginas());
          System.out.println("Tamaño de Página: "+ lector.TamanioPag());
          System.out.println("Listado de Imágenes: "+ lector.LectorImagenes());
          System.out.println("Listado de Fuentes: " + lector.LectordeFuentes());
          this.version.setText(lector.LecturaVersion());
          this.tamanio.setText(String.valueOf(lector.Tamanio()));
          this.numeroPaginas.setText(String.valueOf(lector.Numpaginas()));
          this.tamanioPaginas.setText(lector.TamanioPag());    
          this.imagenes.setText(String.valueOf(lector.LectorImagenes()));
          this.fuentes.setText(lector.LectordeFuentes());
          System.out.println();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Creador;
    private javax.swing.JTextField FechaCreacion;
    private javax.swing.JTextField FechaModificacion;
    private javax.swing.JTextField Productor;
    private javax.swing.JTextField autor;
    private javax.swing.JTextArea fuentes;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField imagenes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField nombreArchivo;
    private javax.swing.JTextField numeroPaginas;
    private javax.swing.JButton seleccionar;
    private javax.swing.JTextField tamanio;
    private javax.swing.JTextField tamanioPaginas;
    private javax.swing.JTextField version;
    // End of variables declaration//GEN-END:variables
}
