/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto01archivos;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo Garcia
 */
public class FormAbrirArchivo extends javax.swing.JFrame {

    /**
     * Creates new form FormAbrirArchivo
     */
    Lista lista = new Lista();
    NodoM aux = new NodoM();
    boolean btn = false;
    public FormAbrirArchivo() {
        initComponents();
        this.setLocationRelativeTo(null);
         guardar.setEnabled(false);
         btnSiguiente.setEnabled(false);
            btnAnterior.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAnterior = new javax.swing.JButton();
        seleccionar1 = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fuentes = new javax.swing.JTextArea();
        autor = new javax.swing.JTextField();
        Creador = new javax.swing.JTextField();
        FechaCreacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        FechaModificacion = new javax.swing.JTextField();
        nombreArchivo = new javax.swing.JTextField();
        Productor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        version = new javax.swing.JTextField();
        tamanio = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        numeroPaginas = new javax.swing.JTextField();
        tamanioPaginasY = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tamanioPaginasX = new javax.swing.JTextField();
        imagenes = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        jLabel3.setText("Autor:");

        jLabel9.setText("Productor:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));

        jPanel1.setBackground(new java.awt.Color(88, 133, 192));

        btnAnterior.setBackground(new java.awt.Color(153, 153, 153));
        btnAnterior.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        btnAnterior.setText("Anterior");
        btnAnterior.setEnabled(false);
        btnAnterior.setName("btnAnterior"); // NOI18N
        btnAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnteriorMouseClicked(evt);
            }
        });

        seleccionar1.setBackground(new java.awt.Color(83, 64, 60));
        seleccionar1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        seleccionar1.setText("Seleccionar");
        seleccionar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionar1MouseClicked(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(192, 175, 125));
        btnSiguiente.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setEnabled(false);
        btnSiguiente.setName("btnSiguiente"); // NOI18N
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
        });

        guardar.setBackground(new java.awt.Color(83, 64, 60));
        guardar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 13)); // NOI18N
        jLabel12.setText("Listado Imagenes:");

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 13)); // NOI18N
        jLabel13.setText("Listado Fuentes:");

        fuentes.setEditable(false);
        fuentes.setColumns(20);
        fuentes.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        fuentes.setRows(5);
        jScrollPane1.setViewportView(fuentes);

        autor.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N

        Creador.setEditable(false);
        Creador.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N

        FechaCreacion.setEditable(false);
        FechaCreacion.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 13)); // NOI18N
        jLabel14.setText("Palabras clave:");

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N

        FechaModificacion.setEditable(false);
        FechaModificacion.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N

        nombreArchivo.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N

        Productor.setEditable(false);
        Productor.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 13)); // NOI18N
        jLabel15.setText("Nombre de Archivo:");

        version.setEditable(false);
        version.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N

        tamanio.setEditable(false);
        tamanio.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel16.setText("mm");

        numeroPaginas.setEditable(false);
        numeroPaginas.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N

        tamanioPaginasY.setEditable(false);
        tamanioPaginasY.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 13)); // NOI18N
        jLabel1.setText("Fecha Modificacion:");

        jLabel17.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel17.setText("X");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 13)); // NOI18N
        jLabel2.setText("Creador:");

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 13)); // NOI18N
        jLabel4.setText("Autor:");

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 13)); // NOI18N
        jLabel5.setText("Productor:");

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 13)); // NOI18N
        jLabel6.setText("Fecha Creacion:");

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 13)); // NOI18N
        jLabel7.setText("Version de PDF:");

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 13)); // NOI18N
        jLabel8.setText("Tamaño del archivo:");

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 13)); // NOI18N
        jLabel10.setText("Tamaño de paginas:");

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 13)); // NOI18N
        jLabel11.setText("Numero de paginas: ");

        tamanioPaginasX.setEditable(false);
        tamanioPaginasX.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N

        imagenes.setEditable(false);
        imagenes.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel18.setText("Bytes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(numeroPaginas, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(version, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(tamanio, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField11)
                                        .addComponent(Productor)
                                        .addComponent(FechaModificacion)
                                        .addComponent(FechaCreacion)
                                        .addComponent(Creador)
                                        .addComponent(autor)
                                        .addComponent(nombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tamanioPaginasY, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tamanioPaginasX, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(seleccionar1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Creador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Productor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tamanioPaginasY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tamanioPaginasX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccionar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        
        NodoM actual=lista.getInicioM();
        while(actual!=null)
        {
            EscritorArchivo escritor = new EscritorArchivo();
            if (actual == lista.getInicioM() && actual == lista.getFinalM()) {
                escritor.setNombre(this.nombreArchivo.getText());
                escritor.setAutor(this.autor.getText());
            } else {
                escritor.setNombre(actual.getNombre());
                escritor.setAutor(actual.getAutor());
            }
            escritor.setCreador(actual.getCreador());
            escritor.setFechaCreacion(actual.getFechaCreacion());
            escritor.setFechaModificacion(actual.getFechaModificacion());
            escritor.setProductor(actual.getProductor());
            escritor.setVersion(actual.getVersion());
            escritor.setTamanio(actual.getTamanio());
            escritor.setPaginas(actual.getPaginas());
            escritor.setTamanioPaginas(actual.getTamaniox(), actual.getTamanioy());
            escritor.setImagenes(actual.getImagenes());
            escritor.setFuentes(actual.getFuentes());
            escritor.escrituraAleatoria();
            actual = actual.getSiguiente();
        }
    
        JOptionPane.showMessageDialog(rootPane, "se guardo correctamente");
        btn = false;
        this.dispose();
    }//GEN-LAST:event_guardarActionPerformed

    private void seleccionar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionar1MouseClicked
        // TODO add your handling code here:
        
        String temp = "";
        JFileChooser pdfruta = new JFileChooser();
        pdfruta.setDialogTitle("Seleccione la carpeta");
        pdfruta.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if (pdfruta.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) 
        {
            File archivo = pdfruta.getSelectedFile();
            if (archivo.isDirectory()) 
            {
                lectorCarpetas(archivo);
                btn = true;
            } else if (archivo.isFile()) 
            {
                //System.out.println(archivo.getName());
                lectorArchivosPDF(archivo);
                btn = true;
            }
        }
    }//GEN-LAST:event_seleccionar1MouseClicked

    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseClicked
        // TODO add your handling code here:
        if (btn) 
        {
            if (aux.getSiguiente() != null) 
            {
                if (aux.getSiguiente() == lista.getFinalM()) 
                {
                    guardar.setEnabled(true);
                    btnSiguiente.setEnabled(false);
                }
                aux = aux.getSiguiente();

                btnAnterior.setEnabled(true);

            } else 
            {
                aux = lista.getFinalM();
                btnSiguiente.setEnabled(false);
                guardar.setEnabled(true);
            }
            this.nombreArchivo.setText(aux.getNombre());
            this.autor.setText(aux.getAutor());
            this.Creador.setText(aux.getCreador());
            this.FechaCreacion.setText(aux.getFechaCreacion());
            this.FechaModificacion.setText(aux.getFechaModificacion());
            this.Productor.setText(aux.getProductor());
            this.version.setText(aux.getVersion());
            this.tamanio.setText(String.valueOf(aux.getTamanio()));
            this.numeroPaginas.setText(String.valueOf(aux.getPaginas()));
            this.tamanioPaginasX.setText(String.valueOf(aux.getTamaniox()));
            this.tamanioPaginasY.setText(String.valueOf(aux.getTamanioy()));
            this.imagenes.setText(String.valueOf(aux.getImagenes()));
            this.fuentes.setText(aux.getFuentes());
            lista.ModificarM(this.nombreArchivo.getText(), this.autor.getText(), aux);
        }
    }//GEN-LAST:event_btnSiguienteMouseClicked

    private void btnAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnteriorMouseClicked
        // TODO add your handling code here:
        if (btn) 
        {
            if (aux.getAnterior() != null) 
            {
                aux = aux.getAnterior();
                guardar.setEnabled(false);
                btnSiguiente.setEnabled(true);
            } else 
            {
                aux = lista.getInicioM();
                btnAnterior.setEnabled(false);
                guardar.setEnabled(false);
            }
            this.nombreArchivo.setText(aux.getNombre());
            this.autor.setText(aux.getAutor());
            this.Creador.setText(aux.getCreador());
            this.FechaCreacion.setText(aux.getFechaCreacion());
            this.FechaModificacion.setText(aux.getFechaModificacion());
            this.Productor.setText(aux.getProductor());
            this.version.setText(aux.getVersion());
            this.tamanio.setText(String.valueOf(aux.getTamanio()));
            this.numeroPaginas.setText(String.valueOf(aux.getPaginas()));
            this.tamanioPaginasX.setText(String.valueOf(aux.getTamaniox()));
            this.tamanioPaginasY.setText(String.valueOf(aux.getTamanioy()));
            this.imagenes.setText(String.valueOf(aux.getImagenes()));
            this.fuentes.setText(aux.getFuentes());
            lista.ModificarM(this.nombreArchivo.getText(), this.autor.getText(), aux);
        }
    }//GEN-LAST:event_btnAnteriorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAbrirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAbrirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAbrirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAbrirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAbrirArchivo().setVisible(true);
            }
        });
    }
    
    private void lectorCarpetas(File archivo)
    {
        String temp = "";
        for (final File fileEntry : archivo.listFiles())
        {
            if (fileEntry.isDirectory()) 
            {
                //System.out.println("leyendo archivos de la caarpeta " + archivo.getAbsolutePath());
                lectorCarpetas(fileEntry);
            } else {
                if (fileEntry.isFile()) 
                {
                    temp = fileEntry.getName();
                    if ((temp.substring(temp.lastIndexOf('.') + 1, temp.length()).toLowerCase()).equals("pdf")) 
                    {
                        //System.out.println("----------------------------------");
                        //System.out.println("Leyendo el pdf: " + fileEntry.getName());
                        String aux = archivo.getAbsolutePath() + "\\" + fileEntry.getName();
                        File archivopdf = new File(aux);
                        lectorArchivosPDF(archivopdf);
                    }
                }

            }
        }
    }
     
    private void lectorArchivosPDF(File archivo)
    {
        String nombre = "";
        String autor = "";
        String creador = "";
        String fechaCreacion = ""; // 23
        String fechaModificacion = ""; // 23
        String productor = "";
        String version = ""; // 8
        int tamanio = 0;
        int paginas = 0;
        float tamaniox = 0;
        float tamanioy = 0;
        int imagenes = 0;
        String fuentes = "";

        LectorPDF lector = new LectorPDF(archivo);
        int a = lector.LecturaMetaDatos().split("/").length;
        String[] partir = lector.LecturaMetaDatos().split("/");
        //System.out.println("Los metadatos son:");
        //this.nombreArchivo.setText(archivo.getName());
        nombre = archivo.getName();
        String b = "";
        String c = "";
        boolean parentesis = false;
        for (int j = 1; j < a; j++) {
            b = "";
            c = "";
            parentesis = false;
            //System.out.println(partir[j]);
            for (int i = 1; i < partir[j].length(); i++) {
                if (partir[j].charAt(i - 1) == '(') {
                    parentesis = true;
                }
                if (parentesis) {
                    if (partir[j].charAt(i) != ')') {
                        b += partir[j].charAt(i);
                    } else {
                        parentesis = false;
                        break;
                    }
                } else {
                    c += partir[j].charAt(i - 1);
                }
            }
            //System.out.println(c);
            if ("Author".equals(c) || "Author ".equals(c)) {
                //System.out.println("Autor: " + b);
                //this.autor.setText(b);
                autor = b;
            } else if ("Creator".equals(c) || "Creator ".equals(c)) {
                //System.out.println("Creador: " + b);
                //this.Creador.setText(b);
                creador = b;
            } else if ("CreationDate".equals(c) || "CreationDate ".equals(c)) {
                //System.out.println("Fecha Creacion: " + b);
                //this.FechaCreacion.setText(b);
                fechaCreacion = b;
            } else if ("ModDate".equals(c) || "ModDate ".equals(c)) {
                //System.out.println("Fecha Modificacion: " + b);
                //this.FechaModificacion.setText(b);
                fechaModificacion = b;
            } else if ("Producer".equals(c) || "Producer ".equals(c)) {
                //System.out.println("Productor: " + b);
                //   this.Productor.setText(b);
                productor = b;
            } else if ("Title".equals(c) || "Title ".equals(c)) {
                //System.out.println("Titulo: " + b);
                //this.autor.setText(b);                 
            }
            //System.out.println(b);
        }

        /*System.out.println("La version del PDF es: " + lector.LecturaVersion());
        System.out.println("Tamaño del archivo: " + lector.Tamanio() + " Bytes");
        System.out.println("Número de Páginas: " + lector.Numpaginas());
        lector.TamanioPag();
        System.out.println("Tamaño de Página: " + lector.getTamanioX() + " X " + lector.getTamanioY() + " mm");
        System.out.println("Listado de Imágenes: " + lector.LectorImagenes());
        System.out.println("Listado de Fuentes: " + lector.LectordeFuentes());*/
        
        version = lector.LecturaVersion();
        tamanio = lector.Tamanio();
        paginas = lector.Numpaginas();
        tamaniox = lector.getTamanioX();
        tamanioy = lector.getTamanioY();
        imagenes = lector.LectorImagenes();
        fuentes = lector.LectordeFuentes();
        lista.InsertarM(nombre, autor, creador, fechaCreacion, fechaModificacion, productor, version, tamanio, paginas, tamaniox, tamanioy, imagenes, fuentes);
        aux = lista.getInicioM();
        if (aux == lista.getFinalM()) {
            guardar.setEnabled(true);
            btnSiguiente.setEnabled(false);
            btnAnterior.setEnabled(false);
            btn = false;
        } else {
            guardar.setEnabled(false);
            btnSiguiente.setEnabled(true);
            btnAnterior.setEnabled(true);
            btn = true;
        }
        this.nombreArchivo.setText(aux.getNombre());
        this.autor.setText(aux.getAutor());
        this.Creador.setText(aux.getCreador());
        this.FechaCreacion.setText(aux.getFechaCreacion());
        this.FechaModificacion.setText(aux.getFechaModificacion());
        this.Productor.setText(aux.getProductor());
        this.version.setText(aux.getVersion());
        this.tamanio.setText(String.valueOf(aux.getTamanio()));
        this.numeroPaginas.setText(String.valueOf(aux.getPaginas()));
        this.tamanioPaginasX.setText(String.valueOf(aux.getTamaniox()));
        this.tamanioPaginasY.setText(String.valueOf(aux.getTamanioy()));
        this.imagenes.setText(String.valueOf(aux.getImagenes()));
        this.fuentes.setText(aux.getFuentes());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Creador;
    private javax.swing.JTextField FechaCreacion;
    private javax.swing.JTextField FechaModificacion;
    private javax.swing.JTextField Productor;
    private javax.swing.JTextField autor;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JTextArea fuentes;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField imagenes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField nombreArchivo;
    private javax.swing.JTextField numeroPaginas;
    private javax.swing.JButton seleccionar1;
    private javax.swing.JTextField tamanio;
    private javax.swing.JTextField tamanioPaginasX;
    private javax.swing.JTextField tamanioPaginasY;
    private javax.swing.JTextField version;
    // End of variables declaration//GEN-END:variables
}
